title: Interpreting & Visualizing Political Data 
description: >- # this means to ignore newlines until "baseurl:"
 AKA Sloppy Stats & Lousy Graphs 
baseurl: "/docs" # the subpath of the site
url: "https://sarah-moore.github.io/nupols_dataviz" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: sarahmoore@u.northwestern.edu 
      link: mailto:sarahmoore@u.northwestern.edu 

  follow:
    - name: Twitter
      link: http://twitter.com/sarahmoreorless
      username: "@sarahmoreorless"
    - name: GitHub
      link: http://github.com/sarah-moore

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
